[package]
name = "decibel_db"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "migrate_up"
path = "./src/bin/migrate_up.rs"

[[bin]]
name = "migrate_down"
path = "./src/bin/migrate_down.rs"

[dependencies]
chrono = "0.4"
dotenv = "0.15"
migaton = { path = "./migaton" }
rusqlite = { version = "0.25", features = [ "bundled", "chrono" ] }
worm_derive = { path = "./worm_derive" }
worm = { path = "./worm" }
